---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment-2
  namespace: demo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-2
  template:
    metadata:
      labels:
        app: microservice-2
    spec:
      containers:
        - name: microservice-2
          image: microservice-2:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: MICROSERVICE_1_URL
              value: "http://microservice-1.demo-namespace.svc.cluster.local:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-2
  namespace: demo-namespace
spec:
  type: NodePort
  selector:
    app: microservice-2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081 