---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: demo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-1
  template:
    metadata:
      labels:
        app: microservice-1
    spec:
      containers:
        - name: microservice-1
          image: microservice-1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: MICROSERVICE_2_URL
              value: "http://microservice-2.demo-namespace.svc.cluster.local:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-1
  namespace: demo-namespace
spec:
  type: NodePort
  selector:
    app: microservice-1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
